spokestack/spokestack-android

- .gitmodules
- README.md
- jni/Android.mk
- jni/Dev.mk
- jni/agc.cpp
- jni/vad.cpp
- pom.xml
- src/main/java/com/pylon/spokestack/OnSpeechEventListener.java
- src/main/java/com/pylon/spokestack/SpeechContext.java
- src/main/java/com/pylon/spokestack/SpeechPipeline.java
- src/main/java/com/pylon/spokestack/SpeechSampler.java
- src/main/java/com/pylon/spokestack/libfvad/package-info.java
- src/main/java/com/pylon/spokestack/wakeword/WakewordTrigger.java
- src/main/java/com/pylon/spokestack/webrtc/AutomaticGainControl.java
- src/main/java/com/pylon/spokestack/webrtc/VoiceActivityDetector.java
- src/main/java/com/pylon/spokestack/webrtc/VoiceActivityTrigger.java
- src/main/java/com/pylon/spokestack/webrtc/package-info.java
- src/test/java/com/pylon/spokestack/SpeechContextTest.java
- src/test/java/com/pylon/spokestack/SpeechSamplerTest.java
- src/test/java/com/pylon/spokestack/google/GoogleSpeechRecognizerTest.java
- src/test/java/com/pylon/spokestack/microsoft/BingSpeechRecognizerTest.java
- src/test/java/com/pylon/spokestack/wakeword/WakewordTriggerTest.java
- src/test/java/com/pylon/spokestack/webrtc/AutomaticGainControlTest.java
- src/test/java/com/pylon/spokestack/webrtc/VoiceActivityDetectorTest.java
- src/test/java/com/pylon/spokestack/webrtc/VoiceActivityTriggerTest.java
Tracing and logging have been added to the spokestack pipeline. Tracing is off by default and can be enabled through the `trace-level` parameter, which defines the minimum tracing level in order of (DEBUG, PERF, and INFO). Logging has been implemented in the SpeechSampler, which will save wav files for speech audio on the device's SD card.
Spokestack has also been modified to use a different repo for the webrtc audio components, which also includes support for automatic gain control, noise suppression, echo suppression, etc. For now, I have integrated AGC, which gives us much better wakeword detector performance, at least on my phone, which does not have built-in AGC (I don't know if any phones do).
The VAD has been decoupled from the wakeword detector and split into detector and trigger …
> tracing, logging, decoupled vad, automatic gain control, pre-emphasis

- src/main/java/com/pylon/spokestack/SpeechContext.java
- src/main/java/com/pylon/spokestack/google/GoogleSpeechRecognizer.java
- src/test/java/com/pylon/spokestack/SpeechContextTest.java
- src/test/java/com/pylon/spokestack/google/GoogleSpeechRecognizerTest.java
This converts the recognize with empty transcript event into an explicit timeout event, for compatibility with the ios wakeword detector/speech recognizer.
> add support for explicit timeout events in the google speech api

- README.md
- pom.xml
- src/main/java/com/pylon/spokestack/tensorflow/TensorflowModel.java
- src/main/java/com/pylon/spokestack/wakeword/WakewordTrigger.java
- src/main/java/com/pylon/spokestack/webrtc/AutomaticGainControl.java
- src/test/java/com/pylon/spokestack/wakeword/WakewordTriggerTest.java
These changes introduce a new tensorflow "encode" model in the wakeword trigger, which allows us to implement autoregressive models for wakeword detection (like rnns and attention). Doing this efficiently requires running each frame through the encoder and then aggregating these frames for attention/classification, in order to avoid redundant calls to the encoder. These models also provide the ability to detect whole phrases with long-range frame dependencies, so we no longer need manual phrasing or smoothing logic and buffers.
This design supports stateful autoregression models (GRU, LSTM, etc.) by maintaining an input/output `state` tensor on the tensorflow model object. CRNN-based encoders with sliding window inputs are also supported, since the mel frames are still maintained in a …
> add support for efficient autoregressive wakeword detection

- src/main/java/com/pylon/spokestack/wakeword/WakewordTrigger.java
- src/test/java/com/pylon/spokestack/wakeword/WakewordTriggerTest.java
Previously, the wakeword trigger would only reset its activation counter whenever it automatically deactivated the pipeline, due to either a timeout or a vad deactivation. However, if the client manually deactivated the pipeline, the counter's state would be retained for the subsequent activation. This would shorten that activation's effective timeout. These changes reset the activation counter whenever the pipeline is inactive.
> reset activation timeout on manual deactivation

- README.md
- jni/Android.mk
- pom.xml
I actually did a deploy before this and realized the artifactId hadn't been updated. I think it'll look better with the platform suffix given the new package structure. Also updated references to Maven Central in the readme and pom.
> Pre-release readme and artifact ID updates

- README.md
- jni/Dev.mk
- src/main/java/io/spokestack/spokestack/OnSpeechEventListener.java
- src/main/java/io/spokestack/spokestack/SpeechContext.java
- src/main/java/io/spokestack/spokestack/SpeechInput.java
- src/main/java/io/spokestack/spokestack/SpeechPipeline.java
- src/main/java/io/spokestack/spokestack/microsoft/BingSpeechRecognizer.java
- src/main/java/io/spokestack/spokestack/package-info.java
- src/main/java/io/spokestack/spokestack/webrtc/AcousticNoiseSuppressor.java
- src/main/java/io/spokestack/spokestack/webrtc/AutomaticGainControl.java
- src/main/java/io/spokestack/spokestack/webrtc/VoiceActivityDetector.java
The `android-native-dependencies` plugin does not allow you to rename the native binaries it downloads; when it copies them to `jniLibs`, it names them with the artifactId. Thus, in order to keep the `spokestack-android` name and have things resolve correctly, we have to name the compiled native libraries to match.
> Rename native library and re-case "Spokestack"

- README.md
- pom.xml
- src/main/java/io/spokestack/spokestack/SpeechInput.java
- src/main/java/io/spokestack/spokestack/tts/SSML.java
- src/main/java/io/spokestack/spokestack/tts/SpokestackTTSClient.java
- src/main/java/io/spokestack/spokestack/tts/TTSCallback.java
- src/main/java/io/spokestack/spokestack/tts/package-info.java
- src/test/java/io/spokestack/spokestack/tts/SpokestackTTSClientTest.java
This is the first version of the Android TTS client. I plan to make it an optional part of the speech pipeline when I integrate the native media player and give callers the option to play the response automatically.
One note: I'm having trouble getting code coverage to work for the `TTSCallback` class, presumably due to the nature of mocking asynchronous network calls. The code does get exercised by the test, but I haven't been able to figure out how to get coverage tools to recognize it. I've decided to leave it for now, but I'm open to any ideas.
> Initial TTS client

- src/main/java/io/spokestack/spokestack/wakeword/RingBuffer.java
- src/test/java/io/spokestack/spokestack/wakeword/RingBufferTest.java
This update allows dependent apps to target Android API
versions lower than 26 that do not have access to all
methods from JDK 1.8.
> Fix: Remove dependency on Math.floorMod from 1.8

- pom.xml
- src/main/java/io/spokestack/spokestack/SpeechConfig.java
- src/main/java/io/spokestack/spokestack/SpeechContext.java
- src/main/java/io/spokestack/spokestack/SpeechPipeline.java
- src/main/java/io/spokestack/spokestack/android/AndroidSpeechRecognizer.java
- src/main/java/io/spokestack/spokestack/android/SpeechRecognizerError.java
- src/main/java/io/spokestack/spokestack/google/GoogleSpeechRecognizer.java
- src/main/java/io/spokestack/spokestack/tts/SpokestackSynthesisResponse.java
- src/test/java/io/spokestack/spokestack/SpeechConfigTest.java
- src/test/java/io/spokestack/spokestack/android/AndroidSpeechRecognizerTest.java
- src/test/java/io/spokestack/spokestack/android/MockRecognizer.java
- src/test/java/io/spokestack/spokestack/android/SpeechRecognizerErrorTest.java
The component itself is fickle and prone to unavailability on (probably many) actual devices and the emulator, but it _does_ provide a free ASR for developers to test with should they have a compliant device.
I'm adding more dependency on Android system components here, and I ended up reducing the Coveralls threshold to 85%, but I think most of that is due to Coveralls not picking up coverage for the new class at all despite it being, as you can see below, painstakingly tested. Should I blame PowerMock? Perhaps, but that is a question for another day.
> Support ASR via Android's built-in SpeechRecognizer

- src/main/java/io/spokestack/spokestack/SpeechOutput.java
- src/main/java/io/spokestack/spokestack/tts/SpokestackTTSOutput.java
- src/main/java/io/spokestack/spokestack/tts/TTSManager.java
- src/test/java/io/spokestack/spokestack/tts/SpokestackTTSOutputTest.java
- src/test/java/io/spokestack/spokestack/tts/TTSManagerTest.java
In keeping with the principle of leaving POJOs out of the configuration object, this PR moves the Android context for the media player into `TTSManager`.
> Store Android Context directly in TTSManager

- src/main/java/io/spokestack/spokestack/tts/SpokestackTTSClient.java
- src/main/java/io/spokestack/spokestack/tts/SpokestackTTSService.java
- src/main/java/io/spokestack/spokestack/tts/TTSCallback.java
- src/main/java/io/spokestack/spokestack/tts/TTSManager.java
- src/test/java/io/spokestack/spokestack/tts/SpokestackTTSClientTest.java
- src/test/java/io/spokestack/spokestack/tts/SpokestackTTSServiceTest.java
- src/test/java/io/spokestack/spokestack/tts/TTSManagerTest.java
As we discussed, there will be no more talk of keys. I found some credentials-related doc to update while I was renaming, so win-win.
> Change references from client "key" to "ID"

- src/main/java/io/spokestack/spokestack/ActivationTimeout.java
- src/main/java/io/spokestack/spokestack/SpeechContext.java
- src/main/java/io/spokestack/spokestack/SpeechPipeline.java
- src/main/java/io/spokestack/spokestack/wakeword/WakewordTrigger.java
- src/main/java/io/spokestack/spokestack/webrtc/VoiceActivityTrigger.java
- src/test/java/io/spokestack/spokestack/ActivationTimeoutTest.java
- src/test/java/io/spokestack/spokestack/SpeechContextTest.java
- src/test/java/io/spokestack/spokestack/SpeechPipelineTest.java
- src/test/java/io/spokestack/spokestack/wakeword/WakewordTriggerTest.java
- src/test/java/io/spokestack/spokestack/webrtc/VoiceActivityTriggerTest.java
This change decouples pipeline ASR activation from the trigger
stages, enabling a hybrid manual/wakeword activation by adding
a new ActivationTimeout component.
The activation length configuration properties have been
renamed to "active-min" and "active-max" to reflect this
change.
In addition, the pipeline now has public methods to control
speech context activation, and when the speech context is activated
or deactivated, it dispatches the corresponding speech event to
listeners internally.
> Breaking: Turn activation timeout into a component

- pom.xml
- src/main/proguard.txt
These rules keep ProGuard from removing Spokestack classes,
which are often loaded dynamically.
Addresses Issue #18.
> Fix: Simple ProGuard rules

- src/main/java/io/spokestack/spokestack/webrtc/VoiceActivityDetector.java
As discussed, this will support upcoming push-to-talk profiles that were getting their pipelines deactivated too aggressively without forcing a non-zero value to be set in every profile.
> Set default vad-fall-delay to 500ms

- src/main/java/io/spokestack/spokestack/android/AndroidSpeechRecognizer.java
- src/test/java/io/spokestack/spokestack/android/AndroidSpeechRecognizerTest.java
- src/test/java/io/spokestack/spokestack/tts/SpokestackTTSOutputTest.java
This update fixes a test for TTS output by injecting a mocked object that should never be garbage collected while the test is running (something that would occasionally trip up the test runner
before). It also "improves" test coverage for the Android ASR component by making it non-final and thus removing the need to modify its byte code for testing.
> Fix flaky test and coverage

- src/main/java/io/spokestack/spokestack/tts/SpokestackSynthesisResponse.java
- src/main/java/io/spokestack/spokestack/tts/SpokestackTTSClient.java
- src/main/java/io/spokestack/spokestack/tts/SynthesisRequest.java
- src/test/java/io/spokestack/spokestack/tts/SpokestackSynthesisResponseTest.java
- src/test/java/io/spokestack/spokestack/tts/SpokestackTTSClientTest.java
This adds support for [Speech Markdown](https://www.speechmarkdown.org/) via Spokestack API's new `synthesizeMarkdown` method, simplifying the formatting needed to customize synthesized text.
> Feature: Speech Markdown support in TTS

- src/main/AndroidManifest.xml
Turns out that if your library doesn't specify a `targetSdkVersion`, Android assumes SDK 1, which results in some extra (suspicious-looking) permissions being requested by default on app install.
API level 8 is specified as the min because that's when the platform `SpeechRecognizer` API was added (not that it'll necessarily be functional on a device that old...).
> Fix: Declare a targetSdkVersion

- src/main/java/io/spokestack/spokestack/android/AndroidSpeechRecognizer.java
- src/test/java/io/spokestack/spokestack/android/AndroidSpeechRecognizerTest.java
- src/test/java/io/spokestack/spokestack/android/MockRecognizer.java
Not much to see here, but I wanted better visibility into some of these things while troubleshooting with new devices, so I figured I'd just make it formal instead of ad hoc print statements.
> Add tracing for Android speech recognizer events

- src/main/java/io/spokestack/spokestack/nlu/NLUContext.java
- src/main/java/io/spokestack/spokestack/nlu/NLUResult.java
- src/main/java/io/spokestack/spokestack/nlu/Slot.java
- src/main/java/io/spokestack/spokestack/nlu/TraceListener.java
- src/main/java/io/spokestack/spokestack/nlu/tensorflow/EncodedTokens.java
- src/main/java/io/spokestack/spokestack/nlu/tensorflow/Metadata.java
- src/main/java/io/spokestack/spokestack/nlu/tensorflow/SlotParser.java
- src/main/java/io/spokestack/spokestack/nlu/tensorflow/TFNLUOutput.java
- src/main/java/io/spokestack/spokestack/nlu/tensorflow/TensorflowNLU.java
- src/main/java/io/spokestack/spokestack/nlu/tensorflow/TextEncoder.java
- src/main/java/io/spokestack/spokestack/nlu/tensorflow/WordpieceTextEncoder.java
- src/main/java/io/spokestack/spokestack/nlu/tensorflow/package-info.java
- src/main/java/io/spokestack/spokestack/nlu/tensorflow/parsers/DigitsParser.java
- src/main/java/io/spokestack/spokestack/nlu/tensorflow/parsers/IdentityParser.java
- src/main/java/io/spokestack/spokestack/nlu/tensorflow/parsers/IntegerParser.java
- src/main/java/io/spokestack/spokestack/nlu/tensorflow/parsers/SelsetParser.java
- src/main/java/io/spokestack/spokestack/nlu/tensorflow/parsers/package-info.java
- src/main/java/io/spokestack/spokestack/util/EventTracer.java
- src/main/java/io/spokestack/spokestack/util/Tuple.java
- src/test/java/io/spokestack/spokestack/nlu/NLUContextTest.java
- src/test/java/io/spokestack/spokestack/nlu/SlotTest.java
- src/test/java/io/spokestack/spokestack/nlu/tensorflow/EncodedTokensTest.java
- src/test/java/io/spokestack/spokestack/nlu/tensorflow/TensorflowNLUTest.java
- src/test/java/io/spokestack/spokestack/nlu/tensorflow/WordpieceTextEncoderTest.java
- src/test/java/io/spokestack/spokestack/nlu/tensorflow/parsers/DigitsParserTest.java
- src/test/java/io/spokestack/spokestack/nlu/tensorflow/parsers/IntegerParserTest.java
- src/test/java/io/spokestack/spokestack/nlu/tensorflow/parsers/SelsetParserTest.java
- src/test/resources/nlu.json
- src/test/resources/vocab.txt
This initial client for the NLU API enables on-device
intent classification and slot recognition via a
pretrained TensorFlow Lite model, metadata, and vocabulary
supplied by the app.
ASR results (or any text) are encoded using the Wordpiece
scheme from Google's BERT model then fed to the TFLite model;
the resulting predictions are parsed into actionable intents and
typed slots using the supplied JSON metadata.
Slot parsers are provided for integer, digits, selset, and entity slots,
and custom slot parsers can be registered by class name.
There is an item or two I'd like to adopt from the iOS interface, so I've
marked this don't merge, but I figured I'd post it now so that review
could start.
> Bert-based on-device NLU

- src/main/java/io/spokestack/spokestack/nlu/tensorflow/EncodedTokens.java
- src/main/java/io/spokestack/spokestack/nlu/tensorflow/TFNLUOutput.java
- src/test/java/io/spokestack/spokestack/nlu/tensorflow/EncodedTokensTest.java
- src/test/java/io/spokestack/spokestack/nlu/tensorflow/WordpieceTextEncoderTest.java
I opted to adjust the punctuation bug upstream instead of making it a selset-specific thing. Punctuation represents separate tokens according to everything but the display-oriented tokenization we're storing in `EncodedTokens`, so it should account for the difference. One can envision other slot types (`date`, for example) that would also want this trimming applied.
One could also argue that `trimPunct` should be the default/only option, but I want to reserve the option to have a lossless version because I'm like that.
> Fix: Trim punctuation for slot value extraction

- src/main/java/io/spokestack/spokestack/nlu/tensorflow/TFNLUOutput.java
- src/test/java/io/spokestack/spokestack/nlu/tensorflow/TensorflowNLUTest.java
After observing results like this in the wild, I decided to make the Android behavior for slots tagged more than once in a classification match the iOS behavior.
> Fix: Allow slot tags to be discontinuous

- src/main/java/io/spokestack/spokestack/nlu/tensorflow/Metadata.java
- src/main/java/io/spokestack/spokestack/nlu/tensorflow/TFNLUOutput.java
- src/main/java/io/spokestack/spokestack/nlu/tensorflow/TensorflowNLU.java
- src/test/java/io/spokestack/spokestack/nlu/tensorflow/TFNLUOutputTest.java
- src/test/resources/nlu.json
This adds support for new features for domain-specific NLU models. Changes are backwards compatible, so there should be no disruption to operation with current models.
- implicit slots at the intent level, which can be overridden by
concrete values in the model output
- name changes for slots specified in the metadata via capture_name
> Support new slot features

- src/main/java/io/spokestack/spokestack/nlu/NLUContext.java
- src/main/java/io/spokestack/spokestack/nlu/tensorflow/TFNLUOutput.java
- src/main/java/io/spokestack/spokestack/nlu/tensorflow/TensorflowNLU.java
- src/test/java/io/spokestack/spokestack/nlu/tensorflow/TFNLUOutputTest.java
- src/test/resources/nlu.json
Instead of throwing an error, if a slot not correlated with the predicted intent is tagged in an utterance, its raw value will be returned instead of the entire classification failing with an error.
This is the change we talked about the other day, which makes sense given our current tagger setup. I did want to retain this as a warning-level log, which necessitated a bit of extra machinery.
> Unknown slot handling

- src/main/java/io/spokestack/spokestack/tts/SpokestackSynthesisResponse.java
- src/main/java/io/spokestack/spokestack/tts/SpokestackTTSService.java
- src/main/java/io/spokestack/spokestack/tts/TTSCallback.java
- src/test/java/io/spokestack/spokestack/tts/SpokestackTTSClientTest.java
Thanks for the bug reports, @noelweichbrodt. `null` TTS audio URLs should no longer be possible, and both GraphQL and HTTP errors should be surfaced as expected via `TTSEvent.Type.ERROR` events.
> Fix: Surface TTS errors to the client via events

- src/main/java/io/spokestack/spokestack/nlu/tensorflow/TensorflowNLU.java
- src/test/java/io/spokestack/spokestack/nlu/tensorflow/TensorflowNLUTest.java
To reduce the time to response on user-submitted classifications, we should warm up the model on initialization, forcing it to allocate its internal resources up front. I opted for a custom `warmup` method to reduce loading time as much as possible—no need to do any Wordpiece encoding or slot parsing here.
Examining the trace messages for classification made me see that I was doing execution timing in an unreliable way for Android, so I fixed that as well.
> Warm up the NLU model before first use

- src/main/java/io/spokestack/spokestack/nlu/Slot.java
- src/main/java/io/spokestack/spokestack/nlu/tensorflow/Metadata.java
- src/main/java/io/spokestack/spokestack/nlu/tensorflow/TFNLUOutput.java
- src/main/java/io/spokestack/spokestack/nlu/tensorflow/TensorflowNLU.java
- src/test/java/io/spokestack/spokestack/nlu/tensorflow/TFNLUOutputTest.java
These are the changes we talked about earlier today. I kept compatibility with the implicit slot and capture name features because they were already here, but we're not currently using them; if they're not in iOS yet, compatibility with the main features here doesn't require adding them:
- Return slots with null values for slots declared by the
metadata but absent from the utterance
- Silently ignore slots spuriously detected by the model
> Feature: Slot output changes

- src/main/java/io/spokestack/spokestack/nlu/tensorflow/TFNLUOutput.java
- src/main/java/io/spokestack/spokestack/nlu/tensorflow/parsers/DigitsParser.java
- src/main/java/io/spokestack/spokestack/nlu/tensorflow/parsers/IntegerParser.java
- src/main/java/io/spokestack/spokestack/nlu/tensorflow/parsers/SelsetParser.java
- src/test/java/io/spokestack/spokestack/nlu/tensorflow/parsers/DigitsParserTest.java
- src/test/java/io/spokestack/spokestack/nlu/tensorflow/parsers/IntegerParserTest.java
- src/test/java/io/spokestack/spokestack/nlu/tensorflow/parsers/SelsetParserTest.java
This change brings spokestack-android into line with the other platform libraries in returning an empty slot value instead of throwing an exception if an error is encountered during parsing.
> Fix: null slot values instead of errors

- src/main/java/io/spokestack/spokestack/ActivationTimeout.java
- src/main/java/io/spokestack/spokestack/SpeechContext.java
- src/main/java/io/spokestack/spokestack/SpeechInput.java
- src/main/java/io/spokestack/spokestack/SpeechPipeline.java
- src/main/java/io/spokestack/spokestack/android/AndroidSpeechRecognizer.java
- src/main/java/io/spokestack/spokestack/android/MicrophoneInput.java
- src/main/java/io/spokestack/spokestack/android/NoInput.java
- src/main/java/io/spokestack/spokestack/android/PreASRMicrophoneInput.java
- src/main/java/io/spokestack/spokestack/android/SpeechRecognizerError.java
- src/main/java/io/spokestack/spokestack/profile/PushToTalkAndroidASR.java
- src/main/java/io/spokestack/spokestack/profile/TFWakewordAndroidASR.java
- src/main/java/io/spokestack/spokestack/profile/VADTriggerAndroidASR.java
- src/test/java/io/spokestack/spokestack/SpeechPipelineTest.java
- src/test/java/io/spokestack/spokestack/android/AndroidSpeechRecognizerTest.java
- src/test/java/io/spokestack/spokestack/android/MicrophoneInputTest.java
- src/test/java/io/spokestack/spokestack/android/MockRecognizer.java
- src/test/java/io/spokestack/spokestack/android/PreASRMicrophoneInputTest.java
This fixes an issue with the AndroidSpeechRecognizer class
that was resulting in no speech being sent to the ASR on
many devices.
It adds new input components capable of releasing the microphone
when ASR is active or avoiding capturing it altogether.
External management of the microphone is communicated via the speech
context; when Spokestack is not managing the microphone, pipeline
stages are not run.
Pipeline stages for the Android ASR profiles have been updated to use these new input classes and avoid unnecessary stages.
The AndroidSpeechRecognizer itself has been updated to manage the speech context where appropriate and to dispatch recognizer timeouts as timeout events instead of errors.
Since part of this changeset touches the foundations of the pipeline, I went ahead and tagged …
> Fix: Microphone sharing for Android ASR

- src/test/java/io/spokestack/spokestack/SpeechPipelineTest.java
`Thread.sleep` considered temperamental.
> fix concurrency issue in test

- src/main/java/io/spokestack/spokestack/SpeechOutput.java
- src/main/java/io/spokestack/spokestack/tts/SpokestackTTSOutput.java
- src/main/java/io/spokestack/spokestack/tts/TTSManager.java
- src/test/java/io/spokestack/spokestack/tts/SpokestackTTSOutputTest.java
- src/test/java/io/spokestack/spokestack/tts/TTSManagerTest.java
Does what it says on the tin. Currently, if you interrupt playback to, say, reactivate the Android ASR (with its signature beep), the TTS will go right on playing after the beep is over. This lets the user decide when TTS should be cut off for good.
> Feature: Allow TTS playback to be stopped

- src/test/java/io/spokestack/spokestack/SpeechPipelineTest.java
`Thread.sleep` _is_ temperamental, but the last PR did not soothe it in the proper way.
> fix test concurrency issue

- src/main/java/io/spokestack/spokestack/OnSpeechEventListener.java
- src/test/java/io/spokestack/spokestack/ActivationTimeoutTest.java
- src/test/java/io/spokestack/spokestack/SpeechContextTest.java
- src/test/java/io/spokestack/spokestack/SpeechPipelineTest.java
- src/test/java/io/spokestack/spokestack/android/AndroidSpeechRecognizerTest.java
- src/test/java/io/spokestack/spokestack/asr/SpokestackCloudRecognizerTest.java
- src/test/java/io/spokestack/spokestack/google/GoogleSpeechRecognizerTest.java
- src/test/java/io/spokestack/spokestack/microsoft/AzureSpeechRecognizerTest.java
- src/test/java/io/spokestack/spokestack/wakeword/WakewordTriggerTest.java
- src/test/java/io/spokestack/spokestack/webrtc/VoiceActivityTriggerTest.java
This is a followup to #75 that extends the annotations to the main speech event. The annotations make Kotlin client code cleaner because you're not forced to declare event parameters as optionals and subsequently unwrap them in your method bodies, but they also sadly indicate a major release because the compiler complains if you have method overrides that _do_ use optionals for params marked with these annotations.
> Feature: add annotations to speech events

- src/main/java/io/spokestack/spokestack/android/AndroidSpeechRecognizer.java
Google seems to have broken offline ASR for calling applications. It's unclear whether this is a bug or intentional, but after removing the request for the offline model, recognition does seem to still work (for now).
> Android ASR fix

- src/main/java/io/spokestack/spokestack/SpeechContext.java
- src/main/java/io/spokestack/spokestack/android/AndroidSpeechRecognizer.java
- src/main/java/io/spokestack/spokestack/asr/SpokestackCloudClient.java
- src/main/java/io/spokestack/spokestack/asr/SpokestackCloudRecognizer.java
- src/main/java/io/spokestack/spokestack/google/GoogleSpeechRecognizer.java
- src/main/java/io/spokestack/spokestack/microsoft/AzureSpeechRecognizer.java
- src/test/java/io/spokestack/spokestack/android/AndroidSpeechRecognizerTest.java
- src/test/java/io/spokestack/spokestack/android/MockRecognizer.java
- src/test/java/io/spokestack/spokestack/asr/SpokestackCloudClientTest.java
- src/test/java/io/spokestack/spokestack/asr/SpokestackCloudRecognizerTest.java
- src/test/java/io/spokestack/spokestack/google/GoogleSpeechRecognizerTest.java
- src/test/java/io/spokestack/spokestack/microsoft/AzureSpeechRecognizerTest.java
This feature passes partial speech recognition results available
from all current ASR providers along to the client for optional
display. It does this by populating the speech context's
transcript with the partial result and firing a new
PARTIAL_RECOGNITION event.
Nothing has changed about the final transcript; it is available
from the speech context when a RECOGNIZE event is fired.
> Feature: Propagate partial ASR results to client

- src/main/java/io/spokestack/spokestack/SpeechPipeline.java
- src/test/java/io/spokestack/spokestack/SpeechPipelineTest.java
This changes the semantics of `SpeechPipeline.start()` to make it
roughly idempotent: If a pipeline is running, `start` will emit an
info trace event, but no error will be thrown.
> Feature: Allow `start` call on a running pipeline

- src/main/java/io/spokestack/spokestack/asr/SpokestackCloudClient.java
- src/main/java/io/spokestack/spokestack/asr/SpokestackCloudRecognizer.java
- src/test/java/io/spokestack/spokestack/asr/SpokestackCloudClientTest.java
- src/test/java/io/spokestack/spokestack/asr/SpokestackCloudRecognizerTest.java
This fixes the usage of Spokestack ASR to comport with server
expectations. Previously, when a websocket was reused for a series
of utterances, an authorization request was only sent on initial
socket connection. It is now sent at the beginning of every utterance.
> Fix: re-authorize Spokestack ASR socket

- src/main/java/io/spokestack/spokestack/nlu/Slot.java
- src/main/java/io/spokestack/spokestack/nlu/tensorflow/TFNLUOutput.java
- src/test/java/io/spokestack/spokestack/nlu/tensorflow/TFNLUOutputTest.java
- src/test/java/io/spokestack/spokestack/nlu/tensorflow/TensorflowNLUTest.java
This change propagates slot types from the Spokestack NLU
metadata to the public Slot API, making them available for
use by other libraries, such as react-native-spokestack,
that wrap this native library.
> Feature: Expose Spokestack NLU slot types

- src/main/java/io/spokestack/spokestack/android/AndroidSpeechRecognizer.java
- src/test/java/io/spokestack/spokestack/android/AndroidSpeechRecognizerTest.java
This is a (hopefully temporary) workaround for a change we've
noticed in the Android ASR behavior. It's started sending
NO_MATCH errors for stretches of inactivity that used to result
in SPEECH_TIMEOUT errors. The former is treated as an actual error
in our library code, but the latter is a plain event, so having
them mismatched causes problems for clients. As a result we're
remapping NO_MATCH errors to timeouts.
> Fix: workaround for Android ASR timeouts

- src/main/java/io/spokestack/spokestack/android/AndroidSpeechRecognizer.java
- src/main/java/io/spokestack/spokestack/android/PreASRMicrophoneInput.java
- src/test/java/io/spokestack/spokestack/android/AndroidSpeechRecognizerTest.java
The Android speech recognizer does not always send events in
the order we originally expected, so the former speech context
management was a bit too aggressive. The Android ASR no longer
deactivates the speech context from within its internal
RecognitionListener until it's sure the interaction is over (via
a final reognition event or an error), and it now handles altering
the context's managed flag instead of leaving that to the microphone
input handler.
> fix: manage speech context better for Android ASR

- src/main/java/io/spokestack/spokestack/ActivationTimeout.java
- src/main/java/io/spokestack/spokestack/SpeechPipeline.java
- src/main/java/io/spokestack/spokestack/SpeechProcessor.java
- src/main/java/io/spokestack/spokestack/SpeechSampler.java
- src/main/java/io/spokestack/spokestack/android/AndroidSpeechRecognizer.java
- src/main/java/io/spokestack/spokestack/asr/SpokestackCloudRecognizer.java
- src/main/java/io/spokestack/spokestack/google/GoogleSpeechRecognizer.java
- src/main/java/io/spokestack/spokestack/microsoft/AzureSpeechRecognizer.java
- src/main/java/io/spokestack/spokestack/wakeword/WakewordTrigger.java
- src/main/java/io/spokestack/spokestack/webrtc/AcousticNoiseSuppressor.java
- src/main/java/io/spokestack/spokestack/webrtc/AutomaticGainControl.java
- src/main/java/io/spokestack/spokestack/webrtc/VoiceActivityDetector.java
- src/main/java/io/spokestack/spokestack/webrtc/VoiceActivityTrigger.java
- src/test/java/io/spokestack/spokestack/SpeechPipelineTest.java
This addresses an issue where internal speech processor state
was available, but stale, after the speech context left the "externally
managed" state, sometimes leading to a false reactivation if
a wakeword activation was pending before the stages' processing
of the audio buffer was interrupted.
Due to the new interface method required by this fix, it will be a major release when ready.
> Fix: reset pipeline stages when context unmanaged

- src/main/java/io/spokestack/spokestack/SpeechContext.java
- src/test/java/io/spokestack/spokestack/SpeechPipelineTest.java
This fixes another issue with microphone handoff between the speech pipeline and Android's built-in ASR. Under certain conditions, it was possible to close the pipeline before the Android ASR had released control of the speech context, rendering the pipeline unable to trigger wakeword or ASR despite reporting successful activation. The speech context is now unconditionally released from external management when the pipeline is stopped, allowing input and stage processing to continue as normal if the pipeline is restarted.
> fix: reclaim speech context on pipeline stop

- src/main/java/io/spokestack/spokestack/SpeechPipeline.java
- src/main/java/io/spokestack/spokestack/android/AudioRecordError.java
- src/main/java/io/spokestack/spokestack/android/MicrophoneInput.java
- src/main/java/io/spokestack/spokestack/android/NoInput.java
- src/main/java/io/spokestack/spokestack/android/PreASRMicrophoneInput.java
- src/test/java/io/spokestack/spokestack/SpeechPipelineTest.java
- src/test/java/io/spokestack/spokestack/android/MicrophoneInputTest.java
- src/test/java/io/spokestack/spokestack/android/PreASRMicrophoneInputTest.java
There are a few different reasons the microphone can fail to read audio, but I'm not sure that any of them are immediately recoverable. To avoid spamming errors to host apps in the `dispatch` loop, this change shuts down the speech pipeline on the first read error, attempting to wrap Android's opaque error codes in the closest they give us to descriptions of those errors.
> fix: stop speech pipeline on audio read errors

- src/main/java/io/spokestack/spokestack/asr/KeywordRecognizer.java
- src/main/java/io/spokestack/spokestack/wakeword/WakewordTrigger.java
The encoder models for the wakeword trigger/keyword recognizer currently use a tanh activation, and all models we have seen have their values for silence driven to the low side of the activation. We want to preserve the lag benefits of filling the encoder buffer on reset, but 0 is an unstable value for this activation, so we will now fill with -1. This reduces false activations.
I also threw in a fix for wakeword tracing that reports the final maximum posterior before activation, instead of the previous maximum.
> change encoder reset fill values

- jni/agc.cpp
- src/main/java/io/spokestack/spokestack/profile/PushToTalkAzureASR.java
- src/main/java/io/spokestack/spokestack/profile/PushToTalkGoogleASR.java
- src/main/java/io/spokestack/spokestack/profile/PushToTalkSpokestackASR.java
- src/main/java/io/spokestack/spokestack/profile/TFWakewordAndroidASR.java
- src/main/java/io/spokestack/spokestack/profile/TFWakewordAzureASR.java
- src/main/java/io/spokestack/spokestack/profile/TFWakewordGoogleASR.java
- src/main/java/io/spokestack/spokestack/profile/TFWakewordSpokestackASR.java
- src/main/java/io/spokestack/spokestack/profile/VADTriggerAndroidASR.java
- src/main/java/io/spokestack/spokestack/profile/VADTriggerAzureASR.java
- src/main/java/io/spokestack/spokestack/profile/VADTriggerGoogleASR.java
- src/main/java/io/spokestack/spokestack/profile/VADTriggerSpokestackASR.java
- src/main/java/io/spokestack/spokestack/webrtc/AutomaticGainControl.java
- src/test/java/io/spokestack/spokestack/webrtc/AutomaticGainControlTest.java
These changes modify the automatic gain control to call webrtc's virtualmic function, which is apparently required for measuring current levels, in spite of the comments. The defaults for AGC have also been tuned to match the levels reported on the iPhone in this new configuration. The AGC hard limiter has also been disabled, because it clips at the target level, which is undesirable when the target level is below full scale.
The AGC has been modified to be placed by default before the noise suppressor, which in my tests gave better noise filtering. This change has been applied to all profiles and should be applied in applications that don't use profiles.
> agc enhancements

- src/main/java/io/spokestack/spokestack/ActivationTimeout.java
- src/main/java/io/spokestack/spokestack/android/AndroidSpeechRecognizer.java
- src/main/java/io/spokestack/spokestack/profile/TFWakewordAzureASR.java
- src/main/java/io/spokestack/spokestack/profile/TFWakewordGoogleASR.java
- src/main/java/io/spokestack/spokestack/profile/TFWakewordSpokestackASR.java
- src/main/java/io/spokestack/spokestack/wakeword/WakewordTrigger.java
- src/test/java/io/spokestack/spokestack/ActivationTimeoutTest.java
This change reverts the names of the configuration parameters that control the pipeline activation length so they are reachable from the React Native library.
The renaming slid through when the activation timeout component was introduced way back when to support both wakeword and push-to-talk activations. I had originally planned to lobby for renaming the params in the RN library, but my inaction will serve as surrender.
I suppose it should be noted that only `wake-active-min` is remotely effective (and that not guaranteed) when the built-in Android ASR is in use.
> fix: Revert active-min/max config keys for RN

- src/main/java/io/spokestack/spokestack/Spokestack.java
- src/main/java/io/spokestack/spokestack/SpokestackAdapter.java
- src/main/java/io/spokestack/spokestack/TranscriptEditor.java
- src/main/java/io/spokestack/spokestack/profile/PushToTalkAndroidASR.java
- src/main/java/io/spokestack/spokestack/profile/PushToTalkAzureASR.java
- src/main/java/io/spokestack/spokestack/profile/PushToTalkGoogleASR.java
- src/main/java/io/spokestack/spokestack/profile/PushToTalkSpokestackASR.java
- src/main/java/io/spokestack/spokestack/profile/TFWakewordAndroidASR.java
- src/main/java/io/spokestack/spokestack/profile/TFWakewordAzureASR.java
- src/main/java/io/spokestack/spokestack/profile/TFWakewordGoogleASR.java
- src/main/java/io/spokestack/spokestack/profile/TFWakewordSpokestackASR.java
- src/main/java/io/spokestack/spokestack/profile/VADTriggerAndroidASR.java
- src/main/java/io/spokestack/spokestack/profile/VADTriggerAzureASR.java
- src/main/java/io/spokestack/spokestack/profile/VADTriggerGoogleASR.java
- src/main/java/io/spokestack/spokestack/profile/VADTriggerSpokestackASR.java
- src/main/java/io/spokestack/spokestack/tts/TTSManager.java
- src/main/java/io/spokestack/spokestack/util/AsyncResult.java
- src/main/resources/checkstyle.xml
- src/test/java/io/spokestack/spokestack/SpokestackTest.java
- src/test/java/io/spokestack/spokestack/nlu/SlotTest.java
- src/test/java/io/spokestack/spokestack/nlu/tensorflow/NLUTestUtils.java
- src/test/java/io/spokestack/spokestack/nlu/tensorflow/TensorflowNLUTest.java
- src/test/java/io/spokestack/spokestack/tts/SpokestackTTSOutputTest.java
- src/test/java/io/spokestack/spokestack/tts/TTSManagerTest.java
- src/test/java/io/spokestack/spokestack/tts/TTSTestUtils.java
This adds a `Spokestack` class that performs setup of all individual subsystems in a central place. It provides a default configuration but allows full client customizability via access to each of the subsystems' individual builders and the subsystems themselves after construction is complete. Individual subsystems can be disabled before building if unwanted.
It also consolidates listening for various Spokestack events into a `SpokestackAdapter` class (inspired by `java.awt.MouseAdapter`) so that clients can extend a single class and handle only events they care about.
Apart from setup convenience, the `Spokestack` wrapper also registers itself as a listener for all subsystems and handles tasks necessary for voice interaction like automatically classifying ASR results (the client will …
> Centralized setup via wrapper class

- src/main/java/io/spokestack/spokestack/tts/SpokestackTTSOutput.java
- src/test/java/io/spokestack/spokestack/tts/SpokestackTTSOutputTest.java
It appears that ExoPlayer can fire state change events for audio
from any source. During development, I noticed seemingly duplicate events
triggered by the Google Assistant deactivation sound. This change prevents
Spokestack PLAYBACK_COMPLETE events from being dispatched unless the
player was known to have received audio from Spokestack when the state
change event occurred.
> fix: don't send irrelevant playback events

- src/main/java/io/spokestack/spokestack/android/AndroidSpeechRecognizer.java
- src/main/java/io/spokestack/spokestack/asr/SpokestackCloudRecognizer.java
- src/main/java/io/spokestack/spokestack/microsoft/AzureSpeechRecognizer.java
- src/test/java/io/spokestack/spokestack/android/AndroidSpeechRecognizerTest.java
- src/test/java/io/spokestack/spokestack/android/MockRecognizer.java
- src/test/java/io/spokestack/spokestack/asr/SpokestackCloudRecognizerTest.java
- src/test/java/io/spokestack/spokestack/microsoft/AzureSpeechRecognizerTest.java
This change makes other speech recognizers match the behavior
of GoogleSpeechRecognizer, which filters out empty strings
before sending partial or full recognition results.
> Fix: don't send empty ASR transcripts

- src/main/java/io/spokestack/spokestack/SpeechPipeline.java
- src/test/java/io/spokestack/spokestack/SpeechPipelineTest.java
This change causes a manual pipeline deactivation to
force all pipeline stages to reset, releasing any resources
they hold. It also performs a full reset on the speech context,
releasing it from any external management registered during
the activation.
This was necessary to support manual deactivation of the
Android speech recognizer, which would otherwise miss
the deactivate event due to its takeover of the speech
context.
@brentspell tagging you to double-check that I'm not missing anything about the intended semantics of the deactivate event and that clearing the transcript, etc., are all acceptable.
> Fix: force pipeline stages to reset on deactivate

- src/main/java/io/spokestack/spokestack/SpeechPipeline.java
- src/main/java/io/spokestack/spokestack/android/AndroidSpeechRecognizer.java
- src/main/java/io/spokestack/spokestack/asr/SpokestackCloudRecognizer.java
- src/main/java/io/spokestack/spokestack/microsoft/AzureSpeechRecognizer.java
- src/test/java/io/spokestack/spokestack/SpeechPipelineTest.java
- src/test/java/io/spokestack/spokestack/android/AndroidSpeechRecognizerTest.java
- src/test/java/io/spokestack/spokestack/asr/SpokestackCloudRecognizerTest.java
- src/test/java/io/spokestack/spokestack/microsoft/AzureSpeechRecognizerTest.java
This change sends a timeout event if an ASR service sends the
empty string as a transcript designated as a "final" result.
Previously only the Google speech recognizer sent a timeout under
these conditions; the other recognizers sent nothing.
I also threw in a demotion in log level for calling `start()` on a 
running pipeline, which really isn't worthy of an `INFO` log.
...and while I was there, I flipped `isPartial` to `isFinal` in
`AndroidSpeechRecognizer` to better match the other
services.
> Fix: send timeout events for empty transcripts

- src/main/java/io/spokestack/spokestack/SpokestackAdapter.java
- src/main/java/io/spokestack/spokestack/SpokestackModule.java
- src/test/java/io/spokestack/spokestack/SpokestackTest.java
This change adds convenience methods to the SpokestackAdapter
abstract class, allowing clients to override methods whose names
are more distinct when implemented together with the others.
Traces and errors are also duplicated from all individual modules
into new purpose-built listener methods.
> Improve facade method readability 

- src/main/java/io/spokestack/spokestack/SpeechPipeline.java
- src/main/java/io/spokestack/spokestack/Spokestack.java
- src/main/java/io/spokestack/spokestack/nlu/NLUContext.java
- src/main/java/io/spokestack/spokestack/nlu/tensorflow/TensorflowNLU.java
- src/main/java/io/spokestack/spokestack/tts/TTSManager.java
- src/test/java/io/spokestack/spokestack/SpokestackTest.java
This change allows clients to remove event listeners for
the NLU and TTS subsystems, extending the capability to the
new Spokestack wrapper.
Previously, only speech pipeline listeners could be removed,
which created a potential memory leak if clients had implemented
the other listeners in ephemeral classes like Activity.
The test uses changes introduced in #111 , so this is a draft until that one is reviewed and merged.
> Allow clients to remove listeners

- src/main/java/io/spokestack/spokestack/Spokestack.java
- src/main/java/io/spokestack/spokestack/SpokestackAdapter.java
- src/main/java/io/spokestack/spokestack/nlu/NLUManager.java
- src/main/java/io/spokestack/spokestack/nlu/NLUService.java
- src/main/java/io/spokestack/spokestack/nlu/tensorflow/TFNLUOutput.java
- src/main/java/io/spokestack/spokestack/nlu/tensorflow/TensorflowNLU.java
- src/main/java/io/spokestack/spokestack/nlu/tensorflow/WordpieceTextEncoder.java
- src/test/java/io/spokestack/spokestack/SpokestackTest.java
- src/test/java/io/spokestack/spokestack/nlu/tensorflow/NLUTestUtils.java
This introduces an NLUManager component capable of dispatching
classification to different backends. It constitutes a breaking
change for the `Spokestack` class since the type of its `nlu`
field has changed.
Slot parsers can now be registered in a `SpeechConfig` object via a `slot-<type>` key mapped to the name of the parser class for that type, like other pluggable Spokestack components.
> breaking: refactor to make NLU interchangeable

- src/main/java/io/spokestack/spokestack/Spokestack.java
- src/main/java/io/spokestack/spokestack/SpokestackAdapter.java
- src/main/java/io/spokestack/spokestack/dialogue/DialogueDispatcher.java
- src/main/java/io/spokestack/spokestack/dialogue/DialogueManager.java
- src/main/java/io/spokestack/spokestack/dialogue/DialoguePolicy.java
- src/main/java/io/spokestack/spokestack/dialogue/policy/RuleBasedDialoguePolicy.java
- src/test/java/io/spokestack/spokestack/dialogue/DialogueManagerTest.java
- src/test/java/io/spokestack/spokestack/dialogue/policy/DialoguePolicyTest.java
These changes update the dialogue manager to be more pluggable like other Spokestack components. The rule-based policy is the default, but another policy can be specified by class name.
In addition, dialogue management is included in the Spokestack wrapper class but is disabled by default. I intend to leave this an undocumented feature for now in anticipation of updates to its design/API, but these changes will support a smooth release, and there are other changes/pending changes on master that need to go out in a release.
> Dialogue wiring

- src/main/java/io/spokestack/spokestack/asr/KeywordRecognizer.java
- src/test/java/io/spokestack/spokestack/asr/KeywordRecognizerTest.java
This change adjusts the KeywordRecognizer to raise a timeout
event when no keyword has been recognized instead of sending
an empty transcript, which brings its behavior in line with other
speech recognizer components.
> fix: timeout event when no keyword is recognized

- src/main/java/io/spokestack/spokestack/tts/SpokestackTTSOutput.java
- src/main/java/io/spokestack/spokestack/tts/TTSEvent.java
- src/test/java/io/spokestack/spokestack/tts/SpokestackTTSOutputTest.java
- src/test/java/io/spokestack/spokestack/tts/TestExoPlayer.java
New TTS events, one of which was requested by @timmywil for use in RN and parallelism with iOS, and one which I added because it made sense once I'd added the other.
Ignore the giant test class I had to add just to fake the event. This event handler can't really be tested directly, and all attempts to mock the player/get a proper test class in place ended in sorrow.
> feat: TTS events for starting/stopping playback

- README.md
- pom.xml
- src/main/java/io/spokestack/spokestack/SpeechOutput.java
- src/main/java/io/spokestack/spokestack/Spokestack.java
- src/main/java/io/spokestack/spokestack/tts/SpokestackTTSOutput.java
- src/main/java/io/spokestack/spokestack/tts/TTSManager.java
- src/test/java/io/spokestack/spokestack/SpokestackTest.java
- src/test/java/io/spokestack/spokestack/tts/SpokestackTTSOutputTest.java
- src/test/java/io/spokestack/spokestack/tts/TTSManagerTest.java
- src/test/java/io/spokestack/spokestack/tts/TTSTestUtils.java
This change stops the built-in TTS player from observing and
responding to Android lifecycle events. An app with multiple
activities will want to decide for itself which events trigger
changes in the TTS system. The new default setting will allow
playback to continue across activity transitions if Spokestack
is established as a long-lived resource not tied to a single
activity/fragment.
Tested locally in a multi-activity app, and this version feels much less disruptive for the reason mentioned above.
> breaking: TTS no longer responds to lifecycle

- src/main/java/io/spokestack/spokestack/SpeechPipeline.java
- src/main/java/io/spokestack/spokestack/Spokestack.java
- src/main/java/io/spokestack/spokestack/nlu/NLUManager.java
- src/main/java/io/spokestack/spokestack/nlu/NLUService.java
- src/main/java/io/spokestack/spokestack/nlu/tensorflow/TensorflowNLU.java
- src/main/java/io/spokestack/spokestack/tts/TTSManager.java
- src/test/java/io/spokestack/spokestack/SpeechPipelineTest.java
- src/test/java/io/spokestack/spokestack/SpeechTestUtils.java
- src/test/java/io/spokestack/spokestack/SpokestackTest.java
- src/test/java/io/spokestack/spokestack/nlu/tensorflow/NLUTestUtils.java
I'd like an API sanity check here—see if the commit message pasted below makes sense. Further explanation: I think we need to keep `Spokestack.start()` and `stop()` limited to interacting with the speech pipeline—a user might want to force the pipeline to stop listening while playing a TTS prompt, so `stop()` can't call `close()` on TTS—but it would also be good to have the ability to fully release all modules' resources if necessary. 
Would it be less surprising if `start()` also ran `prepare()` implicitly?
---
This change makes the NLUService extend AutoCloseable, which forces a
`close()` method on all implementors. The existing service uses this to
release TensorFlow model and vocab resources.
On the NLU manager, `close()` has been duplicated as a convenience
method called `release()`, …
> NLU module updates, threaded through the `Spokestack` wrapper

- pom.xml
This addresses intermittently failing builds at CircleCI by
altering how Maven generates forks for running tests. Values
were derived by trial and error on a Circle VM.
> fix: adjust surefire forking for CI

- src/main/java/io/spokestack/spokestack/tts/SpokestackTTSOutput.java
- src/main/java/io/spokestack/spokestack/util/TaskHandler.java
- src/test/java/io/spokestack/spokestack/tts/SpokestackTTSOutputTest.java
This change moves ExoPlayer preparation and content playing into
the same task when a new TTS URL is received, reducing the possibility
of a race condition in constructing the player when more than one TTS
response becomes available in quick succession.
Additionally, uses of `prepare` and `clear` on the internal media player
and media source have been consolidated to reduce churn.
> fix: tighten task submission in TTS player

- pom.xml
- src/main/java/io/spokestack/spokestack/SpeechPipeline.java
- src/test/java/io/spokestack/spokestack/SpeechPipelineTest.java
- src/test/java/io/spokestack/spokestack/SpokestackTest.java
This is a more comprehensive fix to intermittent
failures at Circle, which persisted after the change
to maven-surefire forking.
Tests that use the full speech pipeline and its accompanying
background thread now automatically clean up that background
thread after the test. Inside the speech pipeline itself, the
background thread has been given a recognizable name and made
responsive to interruption. While this should not be a problem at
runtime under normal usage, the change dramatically reduces
memory usage during tests.
> fix: thread cleanup in test suites

- src/main/java/io/spokestack/spokestack/asr/KeywordRecognizer.java
Experiments have shown that replacing the matchboxnet frontend with a simple convolutional block significantly improves recognition performance, while also reducing the computational burden. Doing so reduces the default receptive field size from 109 frames to 11 frames, which should be used as the default going forward. Existing keyword models for google speech commands and mnist have been deployed for this change.
This change to the default should also be propagated to the ios library @noelweichbrodt.
> reduce keyword recognizer receptive field

- src/main/java/io/spokestack/spokestack/asr/KeywordRecognizer.java
This change matches up the default receptive field for the keyword recognizer's detector model with what is used for training.
> fix default keyword detector receptive field

- src/main/java/io/spokestack/spokestack/profile/PushToTalkSpokestackASR.java
- src/test/java/io/spokestack/spokestack/SpeechPipelineTest.java
Fully qualified class names strike again—at least I came up with a better way to test them this time.
> fix typo in Spokestack ASR profile

- src/main/java/io/spokestack/spokestack/Spokestack.java
- src/test/java/io/spokestack/spokestack/SpokestackTest.java
In order to change the pipeline profile, users currently have to retrieve the pipeline builder and set the profile on _it_, which breaks the call chain of a `Spokestack` builder setup. This change makes it easier to switch from the platform default ASR to, for example, a keyword-based ASR.
> feat: convenience method to set pipeline profile

- src/main/java/io/spokestack/spokestack/asr/KeywordMetadata.java
- src/main/java/io/spokestack/spokestack/asr/KeywordRecognizer.java
- src/test/java/io/spokestack/spokestack/asr/KeywordRecognizerTest.java
- src/test/resources/keyword.json
This change allows keyword classes to be loaded from the model's metadata file, which makes specifying the classes less manual and prone to ordering errors.
> feat: load keyword classes from metadata file

- pom.xml
This addresses an error in the logs on startup when running on Android API 30. The error doesn't appear to affect program functionality, but it can make it look like there are SSL problems. Running with the latest OKHttp eliminates the log.
> update OKHttp dependency

- src/main/java/io/spokestack/spokestack/tts/SpokestackTTSOutput.java
Dumb fix here...the `Spokestack` wrapper resumes the pipeline when it receives an event signaling that playback has stopped, but we only send that event when we know we were playing content, in order to avoid spurious events caused by system sounds, etc.  `resetPlayerState` clears out that knowledge, and it's currently being run in a different thread than (and thus usually/always being executed before) the code that stops the media player.
> fix: ensure pipeline is resumed when tts stops

- src/main/java/io/spokestack/spokestack/Spokestack.java
- src/main/java/io/spokestack/spokestack/dialogue/DialogueManager.java
- src/main/java/io/spokestack/spokestack/dialogue/FinalizedPrompt.java
- src/main/java/io/spokestack/spokestack/dialogue/InMemoryConversationData.java
- src/main/java/io/spokestack/spokestack/dialogue/Prompt.java
- src/main/java/io/spokestack/spokestack/dialogue/policy/RuleBasedDialoguePolicy.java
- src/main/java/io/spokestack/spokestack/rasa/RasaDialoguePolicy.java
- src/main/java/io/spokestack/spokestack/rasa/RasaOpenSourceNLU.java
- src/main/java/io/spokestack/spokestack/rasa/package-info.java
- src/main/resources/checkstyle.xml
- src/test/java/io/spokestack/spokestack/SpokestackTest.java
- src/test/java/io/spokestack/spokestack/dialogue/DialogueManagerTest.java
- src/test/java/io/spokestack/spokestack/dialogue/PromptTest.java
- src/test/java/io/spokestack/spokestack/rasa/RasaDialoguePolicyTest.java
This introduces a basic integration with Rasa's Open Source server via its [webhook API](https://rasa.com/docs/rasa/http-api). Because NLU and dialogue management are both handled by a single request to the server, this includes both an NLU component and a dialogue policy. The Rasa server returns final responses instead of NLU results, so the NLU component here uses a hardcoded intent and metadata in the result that's designed to be interpreted by the dialogue policy.
In the future, we could add a separate Rasa NLU component that uses the `parse` endpoint to get raw NLU results, thus separating NLU from dialogue management, but this version minimizes the effort involved in migrating an existing Rasa chatbot to mobile.
> Rasa Open Source integration

- src/main/java/io/spokestack/spokestack/tts/SpokestackTTSClient.java
- src/main/java/io/spokestack/spokestack/tts/SynthesisRequest.java
- src/main/java/io/spokestack/spokestack/tts/TTSManager.java
- src/test/java/io/spokestack/spokestack/tts/SpokestackTTSClientTest.java
- src/test/java/io/spokestack/spokestack/tts/SpokestackTTSServiceTest.java
- src/test/java/io/spokestack/spokestack/tts/TTSManagerTest.java
- src/test/java/io/spokestack/spokestack/tts/TTSTestUtils.java
I'd like a sanity check on the implementation here to make sure I'm not overcomplicating things. Requests have to be async, so I need to impose some external ordering on the responses.
---
Currently, TTS requests submitted in close proximity
can result in audio being delivered to the client in a
different order than the requests were submitted.
This change keeps the requests asynchronous (as they must
be for Android networking) while enforcing ordering for the
results by introducing a request queue in the TTS manager.
> fix: enforce ordering of TTS responses

- src/main/java/io/spokestack/spokestack/profile/TFWakewordKeywordASR.java
- src/test/java/io/spokestack/spokestack/SpeechPipelineTest.java
This adds a pipeline profile to make it convenient to use a wake word detector combined with keyword ASR, providing TensorFlow-powered offline pipeline activation and limited-vocabulary ASR.
> feat: profile for wakeword + keyword ASR

- src/main/java/io/spokestack/spokestack/nlu/tensorflow/WordpieceTextEncoder.java
A call to a newer (by Android standards) Java method slipped in to the NLU module, making compatibility with Android API < 24 unnecessarily difficult. There's no reason the newer method is needed here, so I'm rolling it back to the old-school way of doing things.
Closes #157 .
> fix: refactor getOrDefault call for API < 24

- src/main/java/io/spokestack/spokestack/asr/EmptyRecognizer.java
- src/main/java/io/spokestack/spokestack/profile/TFWakewordEmptyASR.java
- src/test/java/io/spokestack/spokestack/SpeechPipelineTest.java
- src/test/java/io/spokestack/spokestack/asr/EmptyRecognizerTest.java
This adds a no-op ASR and new pipeline profile for a
wakeword-only use case. Upon successful wakeword
recognition, the pipeline remains active for a single
frame and is then deactivated.
Closes #155.
> feat: wakeword-only profile and empty ASR

- src/main/java/io/spokestack/spokestack/microsoft/AzureSpeechRecognizer.java
- src/main/java/io/spokestack/spokestack/profile/TFWakewordGoogleASR.java
- src/test/java/io/spokestack/spokestack/microsoft/AzureSpeechRecognizerTest.java
I found out during a code review that the Azure ASR component wasn't using a configuration property that it advertised itself as accepting. In testing out that fix, I also discovered we were missing an event listener. I've also adjusted the buffer size to hopefully make the partial results a little snappier and removed the timeout event because Azure seems to like sending empty transcripts after it's already sent (occasionally) complete ones.
In general, the ASR accuracy here isn't what I remember seeing back when the component was first written, but I can get it to work if I speak slowly/clearly enough, and no amount of buffer/stream manipulation on my end has improved performance, so I'm forced to assume that they just have a bad model in production right now or have somehow broken …
> various Azure fixes

- src/main/java/io/spokestack/spokestack/SpeechPipeline.java
- src/test/java/io/spokestack/spokestack/SpeechPipelineTest.java
This ensures that calling `resume` on an unpaused pipeline doesn't hang the pipeline thread.
It also makes `start` act like `resume` on a paused pipeline.
> resume idempotence
